### ISSUE TITLE
Does pylxca work without python2?

### ISSUE THREAD

**Issue by agrare** [lenovo/pylxca#17]
Hello!  We (ManageIQ) have an RPM which packages pylxca (https://github.com/ManageIQ/manageiq-rpm_build/blob/master/packages/python-pylxca/python-pylxca.spec) and we've found that python2 is being pulled in for some reason.  We need to drop this dependency but want to ensure that pylxca will work without python2 installed at at all, and do not have an LXCA system to test with ourselves.

cc @prabhosa any chance you can help out here?
Thanks!

**Comment by agrare** [comment]
We discovered what the issue was, there are two test files which reference python2.7 (https://github.com/lenovo/pylxca/search?q=python2.7) which rpm was picking up on and automatically adding python2 as a dependency.

I will create a pull request to resolve this.

**Comment by prabhosa** [comment]
@agrare  Pylxca latest version tested on python3.  I will get those unit test references fixed.

**Comment by prabhosa** [comment]
> We discovered what the issue was, there are two test files which reference python2.7 (https://github.com/lenovo/pylxca/search?q=python2.7) which rpm was picking up on and automatically adding python2 as a dependency.
> 
> I will create a pull request to resolve this.

did not saw your PR before assigning defect. I just checked and merged it.
